"""add wakatime and leetcode stats

Revision ID: da696d8d5025
Revises: 20250215_initial
Create Date: 2026-05-24 18:05:19.611248

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da696d8d5025'
down_revision: Union[str, None] = '20250215_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leetcode_stats',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('total_solved', sa.Integer(), nullable=False),
    sa.Column('easy_solved', sa.Integer(), nullable=False),
    sa.Column('medium_solved', sa.Integer(), nullable=False),
    sa.Column('hard_solved', sa.Integer(), nullable=False),
    sa.Column('acceptance_rate', sa.Float(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.Column('ranking_percentile', sa.Float(), nullable=False),
    sa.Column('top_languages', sa.JSON(), nullable=True),
    sa.Column('recent_submissions', sa.JSON(), nullable=True),
    sa.Column('activity_calendar', sa.JSON(), nullable=True),
    sa.Column('contest_rating', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leetcode_stats_user_id'), 'leetcode_stats', ['user_id'], unique=False)
    op.create_table('wakatime_stats',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('total_seconds', sa.BigInteger(), nullable=False),
    sa.Column('today_seconds', sa.Integer(), nullable=False),
    sa.Column('week_seconds', sa.Integer(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('editors', sa.JSON(), nullable=True),
    sa.Column('daily_breakdown', sa.JSON(), nullable=True),
    sa.Column('best_day_seconds', sa.Integer(), nullable=False),
    sa.Column('best_day_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wakatime_stats_user_id'), 'wakatime_stats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wakatime_stats_user_id'), table_name='wakatime_stats')
    op.drop_table('wakatime_stats')
    op.drop_index(op.f('ix_leetcode_stats_user_id'), table_name='leetcode_stats')
    op.drop_table('leetcode_stats')
    # ### end Alembic commands ###